{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name | default .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: mysql-abcxzy
    app.kubernetes.io/version: {{ .Chart.appVersion }}
    app.kubernetes.io/project: "CI/CD Engineering"
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/created-by: controller-manager
    vtx-cfs/stack: green
    vtx-cfs/environment: dev
    vtx-cfs/status: live
{{- if .Values.argocd_ingress_annotations }}
  annotations:
{{ toYaml .Values.argocd_ingress_annotations | indent 4 }}
{{- end }}
spec:
  rules:
    - host: {{ .Release.Name }}-{{ .Values.env }}.{{ .Values.dns_suffix }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathtype }}
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: {{ .Values.service.externalPort }}
{{- if .Values.ingress.use_vanity_ingress }}
    - host: {{ .Release.Name }}.{{ .Values.dns_suffix }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathtype }}
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: {{ .Values.service.externalPort }}
{{- end }}
{{ if .Values.ingress.tls }}
  tls:
    - hosts:
      - {{ .Release.Name }}-{{ .Values.env }}.{{ .Values.dns_suffix }}
{{- if .Values.ingress.use_vanity_ingress }}
      - {{ .Release.Name }}.{{ .Values.dns_suffix }}
{{- end }}
{{ end }}
{{- end }}