apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_name }}
{{- if .Values.argocd_service_annotations }}
  annotations:
{{ toYaml .Values.argocd_service_annotations | indent 4 }}
{{- end }}
  labels:
  {{- include "commonLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Values.app_name }}
